### ISSUE TITLE
hlep

### ISSUE THREAD

**Issue by TudorHH3000** [VishalCodez/Fake-Mute-Deafen-#3]
my console wont open with ctrl+shift+I why

**Comment by AceLikesGhosts** [comment]
You can enable the Developer Tools by setting "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING" to true in %appdata%/discord/settings.json.

**Comment by VishalCodez** [comment]
Thanks Dear
